export const STORE_BEER_LIST = 'STORE_BEER_LIST';
export const HANDLE_CURRENT_PAGE_CHANGE = 'HANDLE_CURRENT_PAGE_CHANGE';
export const HANDLE_SEARCHED_BEERS_DETAILS = 'HANDLE_SEARCHED_BEERS_DETAILS';
export const HANDLE_SEARCH_CURRENT_PAGE_CHANGE = 'HANDLE_SEARCH_CURRENT_PAGE_CHANGE';
